### ISSUE TITLE
I-VIPv1.0_py3 problem

### ISSUE THREAD

**Issue by Juandemendieta** [caozhichongchong/I-VIP#3]
Hello..I am having the following problem that i can not solve:

  File "I-VIP.py", line 130, in <module>
    Length.setdefault(str(line).split('\t')[2], float(str(line).split('\t')[2]))
IndexError: list index out of range

I ask you if you can help me...Thanks!!

**Comment by caozhichongchong** [comment]
Hello,

Thanks for asking! Would you please download the latest version and try it again?
Either one will do:
git clone https://github.com/caozhichongchong/I-VIP.git
curl -O https://github.com/caozhichongchong/I-VIP/releases/download/I-VIPv1.1/I-VIP.v1.1.tar.gz
curl -O https://github.com/caozhichongchong/I-VIP/releases/download/I-VIPv1.1/I-VIP.v1.1.zip

If there's still a problem, please feel free to contact me or post here.
Contact: anniz44@mit.edu and/or caozhichongchong@gmail.com

**Comment by Juandemendieta** [comment]
Thanks for the quick reply..
With the new version I have the following problem:

  File "I-VIP.py", line 111
    print 'python scripts / GbffParser.py -i' + str (in_dir) + '-f' + str (args.f) + '\ n'
                                           ^
SyntaxError: invalid syntax

**Comment by caozhichongchong** [comment]
Hi!
Thanks for the update!
I think it’s cause by python >= 3.0. You may try python < 3.0 and I’ll update a version for python >= 3.0 later today.

**Comment by caozhichongchong** [comment]
Just updated python 3.0 trial version
https://github.com/caozhichongchong/I-VIP/releases/download/I-VIPv1.1/I-VIP.v1.1.py3.0.tar.gz 
Please have a try and feel free to contact me if there's any problem.
Thanks!
