### ISSUE TITLE
error about example data

### ISSUE THREAD

**Issue by joy-enzo** [caozhichongchong/I-VIP#4]
Hello, when I run the example data with "python I-VIP.py -i example -f .gbff --ot 1 --g example --a Y --m 1 --t 32 --u diamond --r example/example_output --tc 4,10 --tx taxon.txt 2>err.txt", I got the following problems. could you help me? thank you!

Traceback (most recent call last):
  File "/home/chenyiran/chenyiran/hepeng/software/I-VIP.v1.1.py3/scripts/Integron_annotation.py", line 134, in <module>
    for line in open(os.path.join('database/' + 'SARG.structure.txt'), 'r'):
  File "/home/chenyiran/anaconda2/envs/tormes-1.0/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 234: invalid start byte
Traceback (most recent call last):
  File "/home/chenyiran/chenyiran/hepeng/software/I-VIP.v1.1.py3/scripts/Visualization.py", line 351, in <module>
    for line in open(os.path.join(annotationdir,anno_file),'r'):
FileNotFoundError: [Errno 2] No such file or directory: 'example/example_output/Integron/all.Integron_structure.ClassI.annotated.formated.txt'

**Comment by caozhichongchong** [comment]
Hi,

Thanks for reaching out.

Please download (attached or from the link below) and replace "**database/SARG.structure.txt**".
[SARG.structure.txt](https://github.com/caozhichongchong/I-VIP/files/3907754/SARG.structure.txt)
https://github.com/caozhichongchong/I-VIP/blob/master/database/SARG.structure.txt

If the problem still exists, please feel free to contact me (caozhichongchong@gmail.com).
Thanks again.

**Comment by joy-enzo** [comment]
Hi, thanks for your quick reply. 
After I replace SARG.structure with new SARG.structure.txt, then run  "python I-VIP.py -i example -f .gbff.gz --ot 1 --g example --a Y --m 2 --t 1 --u usearch --r example/example_output --tc 4,10 --tx taxon.txt", I got another err. 
wrong input for --tc
Please input in the format of :start column number, end colum number

what am I suppose to do? 
best rewards.

**Comment by caozhichongchong** [comment]
Hi,

Thanks for trying it and reaching out.
Please re-download I-VIP.py run again
"python I-VIP.py -i example -f .gbff.gz --ot 1 --g example --a Y --m 2 --t 1 --u usearch --r example/example_output --tc 4,10 --tx taxon.txt"
https://github.com/caozhichongchong/I-VIP/blob/master/I-VIP.py

Thanks again!
