### ISSUE TITLE
Antibiotic resistant genes database

### ISSUE THREAD

**Issue by claudelelemaystdenis** [caozhichongchong/I-VIP#5]
Hi!
I tried I-VIP on a few genomes that all contain antibiotic-resistant genes of interest for me. Unfortunately, the ARG database used by the program (SARG) does not contain some of these genes; thus, the program does not annotate them. Would it be possible to use other databases (like CARD) for the annotation?
Thank you for your help,
Claudèle

**Comment by caozhichongchong** [comment]
Hi Claudèle,

Thanks for reaching out!

Unfortunately, version 1 does not have the flexibility for customized ARG database. We'll incorporate this function in version 2.

Option1: 
Directly annotate the integron ORFs (Integron/all.ORFs.ClassI.fasta and Integron/all.ORFs.fasta) by blastp.

Option2:
You could "fool" I-VIP that the new ARG database is **SARG.db.fasta**.
Copy database/SARG.db.fasta* to somewhere else.
Copy the new ARG database into the **database** folder and rename it as SARG.db.fasta.

You also need to prepare the following documents for the new ARG database (also put in the **database** folder).
1. **SARG.db.fasta.length.txt**, the length of each ARG sequence (separated by tab)
Format: https://github.com/caozhichongchong/I-VIP/blob/master/database/SARG.db.fasta.length.txt

2. **SARG.structure.txt**, the annotation of each ARG sequence (separated by tab)
Format: https://github.com/caozhichongchong/I-VIP/blob/master/database/SARG.structure.txt
The genotype and phenotype represent the gene family of an ARG and the antibiotic it resisting.
We use the phenotype to color the ARG in the Phylogram.
If you are not sure about the phenotype, you could keep it as "antibiotic" or "unknown".

3. Remake the blastp database for SARG.db.fasta
`makeblastdb -in database/SARG.db.fasta -dbtype prot`

If you have any questions, please feel free to contact me by email.
caozhichongchong@gmail.com
anniz44@mit.edu

**Comment by claudelelemaystdenis** [comment]
Thanks for your quick answer, I'll try that!
Claudèle

**Comment by caozhichongchong** [comment]
No problem. Good luck!
