### ISSUE TITLE
No results - Blastp files empty

### ISSUE THREAD

**Issue by biobrad** [caozhichongchong/I-VIP#6]
Hi There, 
This is a great tool for identifying integrons, however I have been trying to get it to work and keep having some problems.

I end up with empty files in the Integron folder and also, the location that the script looks for the BLASTP results comes back empty.

Here is the integron files, you can see they are all empty
total 8.0K
drwxrwxr-x 7 harbj019 harbj019 4.0K Jan 31 17:39 ClassI
drwxrwxr-x 7 harbj019 harbj019 4.0K Jan 31 17:39 Other
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.Genbank_annotation.ClassI.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.Genbank_annotation.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.Integrase_seqs.ClassI.fasta
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.Integrase_seqs.fasta
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.Integron_seqs.ClassI.fasta
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.Integron_seqs.fasta
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.Integron_structure.ClassI.annotated.formated.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.Integron_structure.ClassI.annotated.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.Integron_structure.ClassI.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.Integron_structure.annotated.formated.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.Integron_structure.annotated.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.Integron_structure.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.ORFs.ClassI.fasta
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.ORFs.ClassI.fasta.ARG.blast.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.ORFs.ClassI.fasta.ARG.blast.txt.filter.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.ORFs.ClassI.fasta.MRG.blast.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.ORFs.ClassI.fasta.MRG.blast.txt.filter.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.ORFs.fasta
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.ORFs.fasta.ARG.blast.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.ORFs.fasta.ARG.blast.txt.filter.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.ORFs.fasta.MRG.blast.txt
-rw-rw-r-- 1 harbj019 harbj019    0 Jan 31 17:39 all.ORFs.fasta.MRG.blast.txt.filter.txt

here are the results when the files cant be found:

python /home/harbj019/softwarebins/I-VIP.v1.2.py3/scripts/Integron_extraction.py -i /home/harbj019/softwarebins/I-VIP.v1.2.py3/metas --g None --r I-VIP_result --f .fa --o .faa

cat: 'I-VIP_result/Integron/Other/Genbank_annotation/*': No such file or directory
cat: 'I-VIP_result/Integron/Other/Integrase_seqs/*': No such file or directory
cat: 'I-VIP_result/Integron/Other/Integron_structure/*': No such file or directory
cat: 'I-VIP_result/Integron/Other/ORFs/*': No such file or directory
cat: 'I-VIP_result/Integron/Other/Integron_seqs/*': No such file or directory
cat: 'I-VIP_result/Integron/ClassI/Integrase_seqs/*': No such file or directory
cat: 'I-VIP_result/Integron/ClassI/Integron_structure/*': No such file or directory
cat: 'I-VIP_result/Integron/ClassI/ORFs/*': No such file or directory
cat: 'I-VIP_result/Integron/ClassI/Integron_seqs/*': No such file or directory
cat: 'I-VIP_result/Integron/ClassI/Genbank_annotation/*': No such file or directory
Finished integron extraction!
Step4 Finished: integron extraction

python /home/harbj019/softwarebins/I-VIP.v1.2.py3/scripts/Integron_annotation.py -i /home/harbj019/softwarebins/I-VIP.v1.2.py3/metas -f .fa --r I-VIP_result --a Y --t 24 --tx None.norm --blastp blastp

blastp -query I-VIP_result/Integron/all.ORFs.fasta -db database/SARG.db.fasta -out I-VIP_result/Integron/all.ORFs.fasta.ARG.blast.txt -outfmt 6 -evalue 1e-5 -num_threads 24
blastp -query I-VIP_result/Integron/all.ORFs.ClassI.fasta -db database/SARG.db.fasta -out I-VIP_result/Integron/all.ORFs.ClassI.fasta.ARG.blast.txt -outfmt 6 -evalue 1e-5 -num_threads 24

blastp -query I-VIP_result/Integron/all.ORFs.fasta -db database/MRG.db.fasta -out I-VIP_result/Integron/all.ORFs.fasta.MRG.blast.txt -outfmt 6 -evalue 1e-5 -num_threads 24
blastp -query I-VIP_result/Integron/all.ORFs.ClassI.fasta -db database/MRG.db.fasta -out I-VIP_result/Integron/all.ORFs.ClassI.fasta.MRG.blast.txt -outfmt 6 -evalue 1e-5 -num_threads 24

Warning: [blastp] Query is Empty!
Warning: [blastp] Query is Empty!
Warning: [blastp] Query is Empty!
Warning: [blastp] Query is Empty!
Step5 Finished: gene cassettes annotation

I have tried to work back through the scripts to find where the issue could be, and while i am ok with python, I am not as good your scripts!!

Here is how i am running the pipeline:

python I-VIP.py -i metas -f .fa --a Y --t 24 --u diamond --tc None --tx None

in the metas folder i have a single metagenome.fa file.

i have all the necessary software in my path as well:
$ whereis diamond
diamond: /usr/local/bin/diamond
$ whereis prodigal
prodigal: /home/harbj019/miniconda3/envs/bioinfo/bin/prodigal
$ whereis blastp
blastp: /home/harbj019/miniconda3/envs/bioinfo/bin/blastp

any help would be greatly appreciated. 

Thank you again for such a great pipeline!

**Comment by caozhichongchong** [comment]
Hi,

Thank you for reaching out!

I think it could be caused by 1) I-VIP.py cannot find any _.fa_ file in the _metas_ folder; or 2)  _.fa_ files are empty or non-genomic sequencing data; or 3) there are no integrons detected in _.fa_ files.

Is _/home/harbj019/softwarebins/I-VIP.v1.2.py3/metas_ the absolute path to your input?
If so, could you please _ls -lh /home/harbj019/softwarebins/I-VIP.v1.2.py3/metas/_ and send the result to me?
If not, could you please provide the absolute path of your input to I-VIP.py and try it again?
_python I-VIP.py -i **absolute_path_of_your_input** -f .fa --a Y --t 24 --u diamond --tc None --tx None_

Best regards,
Anni

**Comment by biobrad** [comment]
Hi Anni.
Thank you for getting back to me.
I will try using the absolute path to the metas folder.
That is one thing I didn't try.
I will let you know how I go.
Cheers
Brad

**Comment by biobrad** [comment]
Hi Anni,
Same result unfortunately.
I have copied stdout to a file and attached.
[ivip_stdout.txt](https://github.com/caozhichongchong/I-VIP/files/7974436/ivip_stdout.txt)

If it will be helpful, i can share a link to the output results as well.

**Comment by caozhichongchong** [comment]
Hi Brad,

Thank you for trying it out!
Yes, it would be super helpful if you could share the output results with me.

Best regards,
Anni

**Comment by biobrad** [comment]
Hi Anni, 
Here is a link to the files - its about 250meg... the main output data appears to end up in the Temp folder.
https://drive.google.com/file/d/1NLEItqpVtrrCJOGQnxX3HOHjvyyVS3b4/view?usp=sharing

thank you again for your time. 

cheers
Brad

**Comment by caozhichongchong** [comment]
Hi Brad,

Thank you for sharing the output results with me!

According to the stdout and Temp folder, there should be one integron (attC + sul1) on _cracf1.faa_megahit_449365_ in your data, but i-vip did not extract it successfully.

----   --------- ------ -----  ---------------------------------------- ------ ------   --- ----- ----  -----------
Temp/cracf1.faa.add.sul1.usearch.txt:
cracf1.faa_megahit_449365_3	AB104852.1.gene6.p01	100	279	0	0	1	279	1	279	3.72e-202	543
----   --------- ------ -----  ---------------------------------------- ------ ------   --- ----- ----  -----------
ivip_stdout.txt: 
rank     E-value  score  bias  sequence                                  start    end   mdl trunc   gc  description
  (1) !   3.2e-08   46.0   0.0  cracf1.fa____cracf1.faa_megahit_449365_3   2434   2375 -  cm    no 0.58  -
----   --------- ------ -----  ---------------------------------------- ------ ------   --- ----- ----  -----------
 
Could you please _ls -lh /home/harbj019/softwarebins/I-VIP.v1.2.py3/metas/extract/_ for me?
Thank you again!

Best regards,
Anni

**Comment by caozhichongchong** [comment]
Hi Brad,

I realized that i-vip would filter out integrons with <2 attC.
It turns out only one attC was detected in your data (_output/cracf1.fa.Z.max.attc.hits.txt2.txt_), thus i-vip identified no integrons. 
That's why the blastp files were empty (_Warning: [blastp] Query is Empty!_).

I'm sorry that the stdout of i-vip was confusing. 
It should directly clarify that "no integrons were identified", which I would update it in the next version.

Best regards,
Anni
